### ISSUE TITLE
no found sudo.sh

### ISSUE THREAD

**Issue by omegadw** [SchnoppDog/piano-led#1]
pi@raspberrypi:~ $ curl -L https://npmjs.org/install.sh | sudo.sh
bash: sudo.sh: orden no encontrada
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
 92  5450   92  5054    0     0   2157      0  0:00:02  0:00:02 --:--:-- 1002k
curl: (23) Failed writing body (411 != 1369)

**Comment by SchnoppDog** [comment]
Hi there,
thank you for trying my installation with the raspberry pi. I am investigating this problem and I will inform you when the problem has been solved. Unfortunately this may take a while.

**Comment by SchnoppDog** [comment]
The Readme-file has been updated. Try using `sudo apt-get install npm`. This should do the trick.

**Comment by SchnoppDog** [comment]
Closing this issue.
